### PR TITLE
Copy over lab5 changes from labdev

### PR DESCRIPTION
**Pull request by chfont**
Removes call-by-name tests, remove deprecation warnings, update library and Scala versions

### CODE REVIEW

**Comment by vmaravind96** [comment]
Removed Uploading Artifact from Github actions. Sanity tested the jobs.

**Comment by vmaravind96** [comment]
Tested the ref implementation. It works with newly generated answer files.

**Comment by SpenceIsCool** [comment]
Does DoDecl need an additional premise that e1 is not redex subject to mode?

**Comment by SpenceIsCool** [comment]
Please update `pppl-lab5/src/main/scala/jsy/student/Lab5Worksheet.sc` and `pppl-lab5/src/main/scala/jsy/lab5/Meeting19-DoWith.sc` to the new `.worksheet.sc` required format

**Comment by chfont** [comment]
> Please update `pppl-lab5/src/main/scala/jsy/student/Lab5Worksheet.sc` and `pppl-lab5/src/main/scala/jsy/lab5/Meeting19-DoWith.sc` to the new `.worksheet.sc` required format

Oh, They are changed but the original was still in the PR it seems. Removed now as its duplicate.

**Pull request merged**
